[package]
name = "rust_lib_my_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.8.0"
anyhow = "1.0.96"
image = "0.25.5"
async-walkdir = {version = "2.1.0"}
rfd= "0.15.2"
tokio ={ version = "1.43.0", features = ["full"] }
lazy_static = {version = "1.5"}
num_cpus ={ version = "*"}
futures-lite = {version = "*"}

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
