// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<UpdateInfo?> checkUpdate({required String currentVersion}) => RustLib
    .instance
    .api
    .crateApiCheckVersionCheckUpdate(currentVersion: currentVersion);

Future<bool> downloadAndInstall({required UpdateInfo updateInfo}) => RustLib
    .instance
    .api
    .crateApiCheckVersionDownloadAndInstall(updateInfo: updateInfo);

class UpdateInfo {
  final String version;
  final String changelog;
  final String downloadUrl;

  const UpdateInfo({
    required this.version,
    required this.changelog,
    required this.downloadUrl,
  });

  @override
  int get hashCode =>
      version.hashCode ^ changelog.hashCode ^ downloadUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          changelog == other.changelog &&
          downloadUrl == other.downloadUrl;
}
